### ISSUE TITLE
Adding module variable for host model to registry does not compile

### ISSUE THREAD

**Issue by cacraigucar** [gold2718/ccpp-framework#1]
Either I didn't completely implement this correctly, or there is a bug in the framework.  When I moved precl as we discussed, I get the following error during compilation:

/home/cacraig/CPF_proto_new_cam_kessler/cam_driver/bin/ccpp/CAM_ccpp_cap.F90:33:7:

    use cam_kessler_main, only: precl
       1
Fatal Error: Can't open module file ‘cam_kessler_main.mod’ for reading at (1): No such file or directory
compilation terminated.

It looks like cam_kessler_main isn't compiled yet.  Is this another instance like "machines"?

**Comment by gold2718** [comment]
This is a CMake / code structure issue (i.e., I gave you bad information on the phone).
cam[67]_kessler.F90 cannot be built until the framework is built which is why there is no module file. You need to either make a new module  for `precl` (adding that module to `library_files`) or just add it as a public variable in physics_types_cam[67].F90. My future self tells me that the documentation mentions this.
