### ISSUE TITLE
Match ccpp_physics_initialize calling list with hostmodel call

### ISSUE THREAD

**Issue by cacraigucar** [gold2718/ccpp-framework#7]
Currently the host model developer needs to augment their call with the host model data to match the call that is being auto-generated for CAM_ccpp_physics_initialize.  This is not ideal for the developer as there is no way to know what the order is until a cmake is completed.

**Comment by gold2718** [comment]
I do not understand this issue. The host model is in control of what shows up in that interface. Adding items to the registry with no `<module>` tag indicates that the host model intends to pass that quantity in its calls to the host cap. To prevent new arguments from showing up in the host model cap interface, simply add a `<module>` tag.
If this is incorrect, please add a counter-example to this issue, otherwise, please close it.

**Comment by gold2718** [comment]
I do not think this is still an issue (e.g., the registry is long gone).
